spring:
    application:
        name: mscloudgateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowercase-service-id: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscourserealm

server:
    port: 8080

eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://cursoms-eureka-user:password@${EUREKA_SERVER}:8761/eureka
